version: '3.6'

services:
  smart-brain-api:
    container_name: backend
    command: npm start
    build: ./
    working_dir: /usr/src/Async-Component/server 
    environment:
      POSTGRES_URI: postgres://yogi:postg@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/Async-Component/server


  postgres:
    environment:
      POSTGRES_USER: yogi
      POSTGRES_PASSWORD: postg
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432"


  redis:
      image: redis
      ports:
        - "6379"
