version: '3.6'

services:
  smart-brain-api:
    container_name: backend
    command: npm start
    build: ./
    working_dir: /usr/src/Async-Component/server 
    environment:
      POSTGRES_URI: postgres://yogi:postg@postgres:5432/smart-brain-docker
    
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/Async-Component/server


  postgres:
    environment:
      POSTGRES_USER: yogi
      POSTGRES_PASSWORD: postg
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432"
